version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: warehouse_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: warehouse
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d warehouse"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
